#pragma once

/*
   parserTable.h, generated by wbcparse (c) Phillip Voyle 2005 - 2021.
*/

#include <utility>
class CParserTable
{
public:
   enum ActionID {aShift, aReduce, aError};
   enum TokenID{
      tVariableName = 0,
      tAssign = 1,
      tLiteral = 2,
      tIdentifier = 3,
      tBeginRegexp = 4,
      tFinishedRegexp = 5,
      tState = 6,
      tOn = 7,
      tResponse = 8,
      tEOF = 9,
      tOr = 10,
      tPlus = 11,
      tStar = 12,
      tQMark = 13,
      tRegexp = 14,
      tOpen = 15,
      tClose = 16,
      $ = 17,
      ntProgram = 18,
      ntRegexp = 19,
      ntAssignVariables = 20,
      ntAssignDefinitions = 21,
      ntInitStates = 22,
      ntStateAssignment = 23,
      ntInitOneState = 24,
      ntEvents = 25,
      ntEvent = 26
   };
   typedef std::pair<ActionID, unsigned> Action;
private:
   static const unsigned kTerminals = 18;
   static const unsigned kNonterminals = 9;
   static const unsigned kStates = 38;
   static const Action s_actionTable[kStates][kTerminals];
   static const int s_gotoTable[kStates][kNonterminals];
   static const int s_earlyReduce[kStates];
   static const char* s_tokenNames[kTerminals + kNonterminals];
public:
   static const Action& GetAction(int nStateID, int nTerminalID);
   static int GetGoto(int nStateID, int nNonterminalID);
   static int GetEarlyReduce(int nStateID);
   static const char* GetTokenName(TokenID id);
};

