/*
   LALRGenParserTable.cpp, generated by wbcparse (c) Phillip Voyle 2005 - 2021.
*/

#include <assert.h>
#include "LALRGenParserTable.h"

const CLALRGenParserTable::Action CLALRGenParserTable::s_actionTable[CLALRGenParserTable::kStates][CLALRGenParserTable::kTerminals] = {
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 8), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 10)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 9), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 10), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 11), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 12), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 11), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 1)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 13), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 8), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 10)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 13), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 13), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 13), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 13), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 13), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 13), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 13), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 13)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 7), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 2), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 12), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 12), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 12), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 12), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 12), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 12), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 12), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 12)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 9)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 9), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 10), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 11), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 12), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 20), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 3), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 3), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 11), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 12), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 3), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 3), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 4), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 4), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 11), CLALRGenParserTable::Action(CLALRGenParserTable::aShift, 12), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 4), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 4), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 5), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 5), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 5), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 5), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 5), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 5), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 6), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}, 
   {CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 8), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 8), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 8), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 8), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 8), CLALRGenParserTable::Action(CLALRGenParserTable::aReduce, 8), CLALRGenParserTable::Action(CLALRGenParserTable::aError, 0)}
};

const int CLALRGenParserTable::s_gotoTable[CLALRGenParserTable::kStates][CLALRGenParserTable::kNonterminals] = {
   {1, 2, 3, 4, 5}, 
   {-1, -1, -1, -1, -1}, 
   {-1, -1, -1, -1, -1}, 
   {-1, -1, -1, -1, -1}, 
   {-1, -1, -1, -1, -1}, 
   {-1, 2, 14, 4, 5}, 
   {-1, -1, -1, -1, -1}, 
   {-1, 15, -1, -1, -1}, 
   {-1, -1, -1, -1, -1}, 
   {-1, 16, -1, -1, -1}, 
   {-1, 17, -1, -1, -1}, 
   {-1, 18, -1, -1, -1}, 
   {-1, 19, -1, -1, -1}, 
   {-1, -1, -1, -1, -1}, 
   {-1, -1, -1, -1, -1}, 
   {-1, -1, -1, -1, -1}, 
   {-1, -1, -1, -1, -1}, 
   {-1, -1, -1, -1, -1}, 
   {-1, -1, -1, -1, -1}, 
   {-1, -1, -1, -1, -1}, 
   {-1, -1, -1, -1, -1}
};


const int CLALRGenParserTable::s_earlyReduce[CLALRGenParserTable::kStates] = {
   -1, 
   0, 
   -1, 
   1, 
   -1, 
   -1, 
   7, 
   -1, 
   13, 
   -1, 
   -1, 
   -1, 
   -1, 
   12, 
   9, 
   -1, 
   -1, 
   -1, 
   5, 
   6, 
   8
};


const std::string CLALRGenParserTable::s_tokenNames[CLALRGenParserTable::kTerminals + CLALRGenParserTable::kNonterminals] = {
      "tAdd",
      "tSub",
      "tMul",
      "tDiv",
      "tNumber",
      "tLeftBracket",
      "tRightBracket",
      "tEndLine",
      "$",
      "ntProgram",
      "ntExpression",
      "ntLines",
      "ntEvaluatedExpression",
      "ntLine"
};


const CLALRGenParserTable::Action& CLALRGenParserTable::GetAction(int stateID, int tokenID)
{
   assert(stateID >= 0 && stateID < kStates);
   assert(tokenID >= 0 && tokenID < kTerminals);
   return s_actionTable[stateID][tokenID];
}

int CLALRGenParserTable::GetGoto(int stateID, int tokenID)
{
   assert(stateID >= 0 && stateID < kStates);
   assert(tokenID >= kTerminals && tokenID < kTerminals + kNonterminals);
   return s_gotoTable[stateID][tokenID - kTerminals];
}

int CLALRGenParserTable::GetEarlyReduce(int stateID)
{
   assert(stateID >= 0 && stateID < kStates);
   return s_earlyReduce[stateID];
}

std::string CLALRGenParserTable::GetTokenName(CLALRGenParserTable::TokenID id)
{
   assert(id >= 0 && id < kTerminals + kNonterminals);
   return s_tokenNames[id];
}

