/*
    lexigen_table.cpp
    Generated by wbclex Scanner Generator (C) Phillip Voyle 2011 - 2021
*/

#include "lexigen_table.h"

const int CLexigenTable::s_dataOffsets[CLexigenTable::kStates] =
{
    0
};

const int CLexigenTable::s_announceOnEOF[CLexigenTable::kStates] =
{
    9
};

const int CLexigenTable::s_announceData[CLexigenTable::kInnerStates] =
{
   -1,  0,  0,  1,  2,  3,  4,  5,  6,  7,  8, 10,  0
};

const bool CLexigenTable::s_canEarlyAnnounce[CLexigenTable::kInnerStates] = {
   false,
   false,
   false,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   false
};

bool CLexigenTable::CanEarlyAnnounce(int state, int nInnerState)
{
   return s_canEarlyAnnounce[s_dataOffsets[state] + nInnerState];
}

int CLexigenTable::GetAnnounce(int state, int nInnerState)
{
   return s_announceData[s_dataOffsets[state] + nInnerState];
}

int CLexigenTable::GetAnnounceOnEOF(int state)
{
   return s_announceOnEOF[state];
}

int CLexigenTable::GetTransition(int state, int nInnerState, char c)
{
   switch(s_dataOffsets[state]+ nInnerState)
   {
   case 0:
      if ((c == '0')) return 1;
      if ((c == '+')) return 3;
      if ((c == '-')) return 4;
      if ((c == '*')) return 5;
      if ((c == '/')) return 6;
      if ((c == '(')) return 7;
      if ((c == ')')) return 8;
      if ((c == '\n')) return 9;
      if ((c == '\t')
       || (c == ' ')) return 10;
      if ((c >= '1' && c <= '9')) return 2;
      return 11;
   case 1:
      return -1;
   case 2:
      if ((c >= '0' && c <= '9')) return 12;
      return -1;
   case 3:
      return -1;
   case 4:
      return -1;
   case 5:
      return -1;
   case 6:
      return -1;
   case 7:
      return -1;
   case 8:
      return -1;
   case 9:
      return -1;
   case 10:
      return -1;
   case 11:
      return -1;
   case 12:
      if ((c >= '0' && c <= '9')) return 12;
      return -1;
   }
}
